# Generated by Django 2.0.8 on 2018-09-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exer3', '0003_auto_20180904_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=128)),
                ('section', models.CharField(max_length=128)),
            ],
        ),
    ]
